# ETAPA DE LIMPIEZA

In [1]:
import pandas as pd

In [2]:
attacks = pd.read_csv("data/attacks.csv",encoding = "ISO-8859-1")

## Limpieza del DataFrame

Empezamos gestionando los null encontrados en la exploraci√≥n inicial.

   1. Eliminamos columnas "Unnamed: 22" y "Unnamed: 23".

In [3]:
attacks.drop(["Unnamed: 22", "Unnamed: 23"], axis=1, inplace=True)

   2. Eliminamos los registros en los que todos los valores son nulos.

In [4]:
attacks.dropna(how="all", inplace=True)

   3. Eliminamos todos los registros en los que todos los valores sean NaN, excepto el Case Number (no aportan valor).

   3. 1. Eliminamos todos los registros en los que el Case Number sea igual a 0 (porque en principio todos los registros con Case Number = 0 tienen NaN en el resto de valores).

In [5]:
attacks.loc[(attacks["Case Number"] == "0")]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
6302,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6304.0
6303,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6305.0
6304,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6306.0
6305,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6307.0
6306,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6308.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8697,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8698,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8699,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8700,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8701,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
attacks.drop(attacks[(attacks["Case Number"] == "0")].index, inplace=True)

In [7]:
attacks.tail()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8¬∫N, 79¬∫W",NaN,Jules Patterson,M,...,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

   3. 2. Eliminamos el registro con "xx" en la columna "Case Number" porque observamos que el resto de valores son NaN.

In [8]:
attacks.loc[(attacks["Case Number"] == "xx")]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
attacks.drop(attacks[(attacks["Case Number"] == "xx")].index, inplace=True)

In [10]:
attacks.tail()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8¬∫N, 79¬∫W",NaN,Jules Patterson,M,...,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0

   4. Cambiamos el nombre de las columnas para trabajar con ellas sin problemas.

In [11]:
attacks.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order'],
      dtype='object')

In [12]:
attacks.columns = ["case_number", "date", "year", "type", "country", "area", "location", "activity", "name", "sex", "age", "injury", "fatal_y/n", "time", "species", "investigator_or_source", "pdf", "href_formula", "href", "case_number.1", "case_number.2", "original_order"]

In [13]:
attacks.columns # Observamos como los nombres han cambiado.

Index(['case_number', 'date', 'year', 'type', 'country', 'area', 'location',
       'activity', 'name', 'sex', 'age', 'injury', 'fatal_y/n', 'time',
       'species', 'investigator_or_source', 'pdf', 'href_formula', 'href',
       'case_number.1', 'case_number.2', 'original_order'],
      dtype='object')

   5. Eliminamos "Case Number 1" y "Case Number 2" si comprobamos que esta informaci√≥n no aporta valor.

- Comprobamos si estas columnas son duplicados de "Case Number" (motivo de eliminaci√≥n directa).

In [14]:
attacks["case_number"].equals(attacks["case_number.1"])

False

In [15]:
attacks["case_number"].equals(attacks["case_number.2"])

False

In [16]:
attacks["case_number.1"].equals(attacks["case_number.2"])

False

   Observamos que esta hip√≥tesis no se cumple.
   
   Aun as√≠, confirmamos que las dos columnas pretenden asignar un ID √∫nico a cada registro (algo que ya hace "Case Number"). No nos aportan informaci√≥n adicional, por lo que decidimos eliminar las columnas (no podremos hacerlo a trav√©s de m√©todos relacionados con duplicates porque no son duplicados, as√≠ que lo haremos mediante .drop

In [17]:
attacks.drop(["case_number.1", "case_number.2"], axis=1, inplace=True)

In [18]:
attacks.sample(50) # Observamos como las columnas se han eliminado.

,case_number,date,year,type,country,area,location,activity,name,sex,age,injury,fatal_y/n,time,species,investigator_or_source,pdf,href_formula,href,original_order
63,2017.11.13,13-Nov-2017,2017.0,Unprovoked,AUSTRALIA,New South Wales,Avoca Beach,Surfing,Charlie Fry,M,25,Puncture wounds to left shoulder,N,16h00,2 m shark,"B. Myatt, GSAF",2017.11.13-Fry.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6240.0
686,2013.04.10,10-Apr-2013,2013.0,Unprovoked,FRENCH POLYNESIA,Tuamotus,"North Pass, Fakarava",Kite boarding,Nick Eitel,M,53,"Underside of board, fins and, harness were dam...",N,12h00,Possibly a blacktip reef shark,N. Eitel,2013.04.10-Eitel.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5617.0
3613,1965.08.30,30-Aug-1965,1965.0,Invalid,PHILIPPINES,NaN,"Grounded off Scarborough Shoals, 150 miles nor...","Arsinoe, a French tanker",French seaman,M,NaN,"One man was lost, but he may have drowned",NaN,NaN,Shark involvement not confirmed,"Manila Daily Bulletin, 9/3/1965; SAF Case #1388",1965.08.30-Arsinoe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2690.0
237,2016.07.27,27-Jul-2016,2016.0,Provoked,USA,Florida,"Florida Keys, Monroe County",Lobstering,Warren Sapp,M,43,Laceration to left forearm PROVOKED INCIDENT,N,NaN,"Nurse shark, 4'","Tampa Bay Times, 7/27/2016",2016.07.27-Sapp.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6066.0
4091,1959.06.14.a,14-Jun-1959,1959.0,Unprovoked,USA,California,"La Jolla, San Diego County",Free diving for abalone,Robert Pamperin,M,33,"FATAL, body not recovered",Y,17h10,"Reported to involve a White shark, 6 m to 7m [...","D. Miller & R. Collier; R. Collier, pp. 21-24",1959.06.14.a-Pamperin_Collier.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2212.0
3788,1962.10.06,06-Oct-1962,1962.0,Invalid,USA,California,2 miles off Santa Catalina Island,"Overcome by CO fumes, fell overboard from 36' ...",Marian Leaf,F,43,Drowned due to CO2 poisoning - Post Mortem sca...,NaN,NaN,Shark involvement prior to death was not confi...,"Long Beach Independent, 10/9/1962; H.D. Baldri...",1962.10.06-Leaf.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2515.0
3604,1965.11.03.a,03-Nov-1965,1965.0,Unprovoked,AUSTRALIA,Queensland,Oak Beach,Surfing,Roy McGuffie,M,24,Puncture wounds to right thigh,N,16h30,"Grey nurse shark, 2.4 m [8']","Telegraph (Sydney), Mirror (Sydney), Post (Cai...",1965.11.03.a-McGuffie.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2699.0
5552,1900.11.14,14-Nov-1900,1900.0,Unprovoked,SOUTH AFRICA,Western Cape Province,Three Anchor Bay,Swimming,William Strathorn,M,30,"FATAL, legs severed",Y,NaN,NaN,"P. Logan; M. Levine, GSAF",1900.11.14-Strathorn.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,751.0
562,2014.04.24,24-Apr-2014,2014.0,Unprovoked,AUSTRALIA,Western Australia,"South Passage, south of Coral Bay",Spearfishing,male,M,NaN,Minor injury,N,NaN,reef shark?,"9 News, 4/24/2014",2014.04.24-WA.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5741.0
1529,2005.11.15,15-Nov-2005,2005.0,Provoked,SOUTH AFRICA,Eastern Cape Province,Aston Bay,Fishing for sharks,Ivan Gerger,M,32,Lacerations to hands & right leg when he tried...,N,14h00,"Raggedtooth shark, 2.5m",J. Visser,2005.11.15-Gerger.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,4774.0
1339,2007.08.28.a,28-Aug-2007,2007.0,Unprovoked,USA,California,"Marina State Beach, Monterey County",Surfing,Todd Endris,M,24,Lacerations to thigh & torso,N,10h45,"White shark, 12'",R. Collier,2007.08.28.a-Endris.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,4964.0
1747,2003.09.12,12-Sep-2003,2003.0,Unprovoked,SOUTH AFRICA,Western Cape Province,Near the wreck of the Kakapo off Noordhoek Beach,Body boarding,David Bornman,M,19,"FATAL, left thigh, buttocks, back of spine, ab...",Y,14h30,White shark,"E. Ritter, GSAF; http://www.wavescape.co....",2003.09.12-Bornman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,4556.0
1094,2009.09.01,01-Sep-2009,2009.0,Provoked,SOLOMON ISLANDS,Makira-Ulawa Province,"Kirakira, Makira Island (formerly San Cristobal)",Fishing,male,M,NaN,Injuries to face & neck PROVOKED INCIDENT,N,NaN,NaN,"Solomon Star, 9/4/2009",2009.09.01-Kirakira.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5209.0
2170,1998.08.23.R,Reported 23-Aug-1998,1998.0,Unprovoked,USA,Virginia,Virginia Beach,Spearfishing,male,M,NaN,Lacerations to left hand,N,NaN,"Dusky shark, 12'",Dan,1998.08.23.R-VirginiaBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,4133.0
1368,2007.06.30.a,30-Jun-2007,2007.0,Unprovoked,USA,California,"Will Rogers State Beach, Los Angeles County",Swimming,Katina Zinner,F,NaN,Hand bitten,N,10h00,NaN,R. Collier,2007.06.30.a-Zinner.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,4935.0
527,2014.07.22,22-Jul-2014,2014.0,Unprovoked,REUNION,Saint-Leu,NaN,Surfing,Vincent Rintz,M,51,Lacerations to right wrist & calf,N,15h00,1.8 metre shark,"BFM-tv, 7/22/2014",2014.07.22-Rintz.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5776.0
1968,2001.04.02.a,02-Apr-2001,2001.0,Unprovoked,AUSTRALIA,New South Wales,Nambucca River Entrance,Surfing,Richard Ellis,M,40,Calf bitten,N,10h00,Bronze whaler shark,"T. Peake, GSAF",2001.04.02.a-Ellis.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,4335.0
1939,2001.06.12,12-Jun-2001,2001.0,Unprovoked,USA,Texas,Padre Island National Seashore,Swimming,Jared Black,M,14,Leg lacerated,N,NaN,1.5 m [5'] shark,"Houston Chronicle, 6/17/2001",2001.06.12-Black.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,4364.0
2787,1987.02.28,28-Feb-1987,1987.0,Unprovoked,USA,Florida,"Singer Island, Riviera Beach, Palm Beach County",Windsurfing,Gary Landwirth,M,NaN,"Lacerations to toe, heel & ankle of right foot",N,NaN,Spinner shark,"Sun Sentinel.¬†Fort Lauderdale,¬†3/2/1987,¬†p.¬†4B",1987.02.28-Landwirth.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,3516.0
750,2012.08.28,28-Aug-2012,2012.0,Unprovoked,AUSTRALIA,Western Australia,Red Bluff near Quobba Station,Surfing,Jon Hines,M,34,Lacerations to torso and arm,N,15h30,NaN,"T. Peake, GSAF",2012.08.28-Hines.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5553.0
1293,2008.01.29,29-Jan-2008,2008.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,"Suncoast Pirates Beach, Durban",Surf-skiing,Wayne Symington,M,42,"No injury to surf-skiier, shark holed ski",N,NaN,"Blacktip shark, 2m","The Mercury, 2/1/2008",2008.01.29-Symington.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5010.0
6144,1776.00.00.R,Reported 1776,1776.0,Unprovoked,GUINEA,NaN,NaN,Murder,African slave,M,NaN,FATAL,Y,NaN,NaN,T. Pennant,1776.00.00.R-Slave.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,159.0
317,2016.01.11.R,Reported 11-Jan-2016,2016.0,Unprovoked,AUSTRALIA,Queensland,"Happy Valley Beach, Caloundra",Surfing,Shane Hilder,M,NaN,Laceration to right foot,N,NaN,Wobbegong shark,"ABC Sunshine Coast, 1/11/2016",2016.01.11.R-Hilder.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5986.0
5035,1930.09.26.R,Reported 26-Sep-1930,1930.0,Unprovoked,HONDURAS,Black River,NaN,Swimming,Indian guide,M,NaN,FATAL,Y,NaN,NaN,"NY Times, 9/26/1930",1930.09.26.R-IndianGuide.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1268.0
637,2013.08.18,18-Aug-2013,2013.0,Unprovoked,USA,Hawaii,Pohoiki,Surfing,Jimmy Napeahi,M,16,Lacerations to buttocks & thigh,N,13h00,NaN,"T. Mori, KHON2, 8/18/2013",2013.08.18-Napeahi.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5666.0
4740,1941.08.01,01-Aug-1941,1941.0,Unprovoked,USA,South Carolina,Sullivan's Island at entrance to Charleston Ha...,Swimming at edge of channel,"Howard E. Sweatmon, a soldier",M,20,Chest lacerated,N,NaN,NaN,"V.M. Coppleson (1958), p.153; T. Helm, p.226; ...",1941.08.01-Sweatmon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1563.0
4762,1940.09.00,Sep-1940,1940.0,Unprovoked,PANAMA,Panama Bay (Pacific Ocean),Otoque Island,Bathing,Roberto Menacho,M,18,FATAL,Y,NaN,5.5 m [18'] shark,"V.M. Coppleson (1958), p.263",1940.09.00-Menacho.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1541.0
500,2014.09.09,09-Sep-2014,2014.0,Unprovoked,AUSTRALIA,New South Wales,"Clarkes Beach, Byron Bay",Swimming,Paul Wilcox,M,50,FATAL,Y,10h45,7' shark,"BBC, 9/9/2014",2014.09.09-Wilcox.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5803.0
424,2015.05.15,15-May-2015,2015.0,Unprovoked,USA,South Carolina,Sullivan's Island,NaN,male,M,30,Laceration to foot,N,14h15,6' shark,"News 2, 5/15/2015",2015.05.15-Sullivans.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5879.0
6195,ND-0132,Before 1900,0.0,Provoked,INDIA,NaN,NaN,NaN,male,M,NaN,Cut to arm while roping shark PROVOKED INCIDENT,N,NaN,NaN,Naval Journal (undated),ND-0132-India-fight-with-shark.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,108.0
5564,1899.12.18,18-Dec-1899,1899.0,Unprovoked,AUSTRALIA,Queensland,Tingalpa Creek,Fell into the water,J. Richardson,M,NaN,bite to lower leg,N,Afternoon,NaN,"Brisbane Courier, 12/21/1899",1899.12.18-Richardson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,739.0
6228,ND.0085,"No date, Before 1969",0.0,Unprovoked,RED SEA?,NaN,NaN,Free diving,Jill Reed,F,NaN,"Shoulder scratched, swim fin bitten",N,Morning,NaN,"Captain T. Falcon-Barker, pp. 91-93",ND-0085-JillReed.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,75.0
591,2013.12.16,16-Dec-2013,2013.0,Unprovoked,SOUTH AFRICA,Western Cape Province,Die Platt,Surfing,Thomas Browne,M,19,Injuries to left thigh,N,08h45,"White shark, 3m","Cape Argus, 12/16/2013",2013.12.16-Browne.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5712.0
1869,2002.04.12,12-Apr-2002,2002.0,Unprovoked,AUSTRALIA,New South Wales,"Bar Beach, Newcastle",Swimming,John Schneider,M,45,Foot bitten,N,18h30,NaN,"T. Peake, GSAF",2002.04.12-Schneider.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,4434.0
3256,1974.08.23,23-Aug-1974,1974.0,Unprovoked,HONG KONG,Mirs Bay,NaN,Freedom Swimming,male,M,22,Survived,N,NaN,NaN,"Washington Post, 8/24/1974,p.D6",1974.08.23-FreedomSwimmer.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,3047.0
5990,1858.04.04,04-Apr-1858,1858.0,Unprovoked,TOBAGO,NaN,Rocky Bay,Bathing,John Williams,M,NaN,"Leg bitten, surgically amputated",N,NaN,NaN,"C. Moore, GSAF",1858.04.04-Williams.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,313.0
5343,1914.03.03,03-Mar-1914,1914.0,Unprovoked,USA,Hawaii,"Honomu, Hawai'i",Washed into sea while picking opihi & attacked...,Okomoto,M,NaN,FATAL,Y,NaN,NaN,C.H. Townsend,1914.03.03-Okomoto.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,960.0
6132,1800.00.00,1800,1800.0,Unprovoked,SEYCHELLES,St. Anne,NaN,a corsair's boat was overturned,NaN,F,NaN,"FATAL, all onboard were killed by sharks",Y,NaN,NaN,V. C. Harvey-Brain,1800.00.00-Corsair-boat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,171.0
650,2013.07.28.a,28-Jul-2013,2013.0,Unprovoked,BAHAMAS,Abaco Islands,Grand Cay,Diving,male,M,50,Bitten on rear lower extremities,N,11h15,NaN,"News Channel 5, 7/28/2013",2013.07.28.a-Bahamas.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5653.0
2829,1986.02.01,01-Feb-1986,1986.0,Unprovoked,AUSTRALIA,Victoria,Jan Juc Beach,Surfing,David Adams,M,29,"No injury, knocked into water & board bitten",N,06j00,"Bronze whaler shark, 3.5 m","Sun, 2/3/1986, p.4",1986.02.01-Adams.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,3474.0
4539,1948.09.17.R,Reported 17-Sep-1848,1848.0,Unprovoked,TURKEY,Adana Province,Yumurtalik,Swimming,Ali Kaymaz,M,NaN,FATAL,Y,NaN,NaN,"C. Moore, GSAF",1948.09.17.R-Kaymaz.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1764.0
6075,1837.09.03,09-Sep-1837,1837.0,Unprovoked,USA,South Carolina,"Magwoods Wharf, Charleston Harbor, Charleston ...",Bathing,a young boy from the Plymouth,M,NaN,Right foot bittten,N,NaN,NaN,"C. Creswell, GSAF; J. Hair, pp.65-66",1837.09.03-Plymouth-boy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,228.0
5614,1897.00.00.b,1897,1897.0,Unprovoked,NEW ZEALAND,NaN,NaN,NaN,Maori male,M,NaN,Lacerations to left arm,N,NaN,NaN,"Deseret News, 6/28/1946",1987.00.00.b-Maori.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,689.0
4586,1947.02.00,Feb-1947,1947.0,Unprovoked,BRAZIL,Rio de Janeiro,Copacabana,Bathing,NaN,NaN,NaN,FATAL,Y,NaN,NaN,"Globo, 5/7/1997",1947.02.00-Brazil.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1717.0
2246,1997.07.02.R,2-Jul-1997,1997.0,Unprovoked,BRAZIL,Pernambuco,Paiva,Surfing,Jurandir Amorim Silva,NaN,NaN,Right thigh bitten,N,NaN,NaN,"D. Duarte; Globo, 7/2/1997",1997.07.02-Jurandir.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,4057.0
4154,1958.07.00.b,Jul-1958,1958.0,Unprovoked,BAHAMAS,Abaco Islands,North of Walkers Cay,"Spearfishing, had fish on his spear",Stanton Waterman,M,36,"No injury, shark went for diver's leg & missed...",N,12h00,"Tiger shark, <2 m TL","S. Waterman, GSAF",1958.07.00.b-Waterman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2149.0
3207,1975.10.04,04-Oct-1975,1975.0,Invalid,USA,California,"Seal Beach, Orange County",Surfing,NaN,NaN,NaN,NaN,NaN,NaN,Questionable incident,Unconfirmed Report,1975.10.04-NV-California.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,3096.0
1577,2005.06.18,18-Jun-2005,2005.0,Invalid,USA,Hawaii,Maui,Swimming,Brad Grissom,M,49,"No injury, 2.1m [7'] tiger shark approached sw...",NaN,08h00,Invalid,www.mauinews.com,2005.06.18-Grissom.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,4726.0
3321,1972.10.14.b,14-Oct-1972,1972.0,Unprovoked,USA,US Virgin Islands,"St. Croix, Cane Bay",Scuba diving,Rodney Temple,M,NaN,"FATAL, body not recovered",Y,NaN,Oceanic whitetip shark x 2,"H.D. Baldridge, pp.177 & 185",1972.10.14.b-Temple.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2982.0
5739,1887.10.00,October 1887,1887.0,Sea Disaster,BAHAMAS,NaN,NaN,"Sea disaster, wreck of the Alfred Watts",Burgess & 2 seamen,M,NaN,FATAL,Y,NaN,NaN,"New York Times, 12/23/1887",1887.10.00-Shipwreck-Alfred-Watts.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,564.0

In [19]:
attacks.to_csv("data/attacks_clean.csv", index=False) # Exportamos el DataFrame para guardar los datos con los avances de limpieza.

In [20]:
attacks = pd.read_csv("data/attacks_clean.csv",encoding='UTF-8') # Encoding sirve para leer el csv sin errores.

   6. Procedemos a limpiar la columna **"activity"**

Antes de nada comprobamos si hay valores NaN.

In [21]:
pd.isnull(attacks["activity"]).sum() # Encontramos 544 NaN en este columna.

544

Rellenamos los valores nulos con el string "unknown" para poder trabajar con ello.

In [22]:
attacks.activity.fillna("unknown",inplace=True)

In [23]:
pd.isnull(attacks["activity"]).sum() # Comprobamos que ya no existen valores nulos.

0

Ahora que ya no tenemos valores nulos, seguimos con la limpieza de la columna.

In [24]:
list(attacks.activity.unique()) # Observamos una enorme cantidad de valores √∫nicos (1533 exactamente) --> Tenemos que agrupar las actividades en un menor n√∫mero de posibles valores.

['Paddling',
 'Standing',
 'Surfing',
 'Free diving',
 'Kite surfing',
 'Swimming',
 'Fishing',
 'Walking',
 'Feeding sharks',
 'Boogie boarding',
 'Scuba diving',
 'Paddle-skiing',
 'Body boarding',
 'Windsurfing',
 'Stand-Up Paddleboarding',
 'Wading',
 'Scuba Diving',
 'Kayak fishing for sharks',
 'Cleaning fish',
 'Snorkeling',
 'Spearfishing',
 'unknown',
 'Diving',
 'Fishing / Wading',
 '2 boats capsized',
 'Night bathing',
 'Surfing ',
 'Kayaking / Fishing',
 'Kayaking',
 'Body surfing',
 'Swimming, poaching abalone',
 'Canoeing',
 'SUP',
 'Skimboarding',
 'Touching a shark',
 'Fishing ',
 'Attempting to lasso a shark',
 'Photo shoot',
 'Paddle boarding',
 'Kakaying',
 'Washing hands',
 'Grabbing shark for a selfie',
 'Kayak fishing',
 'Tagging sharks',
 'Surf skiing ',
 'Surf fishing',
 'Floating',
 'Cage Diving',
 'Surfng',
 'SUP Foil boarding',
 'Lobstering',
 'Fishing in Alabama Deep Fishing Rodeo',
 'Fishing for squid',
 'Fishing for sharks',
 'Floating in tube',
 'Teasing a shark',
 'Surf-skiing',
 'Diving for beche-de-mer',
 'Feeding stingrays?',
 'Kayak Fishing',
 'Sea disaster',
 'Lobster fishing',
 'Swimming / Wading',
 'Fishing for shrimp',
 'Photographing fish',
 'Scallop diving on hookah',
 'Treading water',
 'Body boarding ',
 'Playing in the water',
 'Body Boarding',
 'Body surfing?',
 'Playing',
 'Attempting to rescue a shark',
 'Photographing the shark',
 'Standing / Snorkeling',
 'Hand feeding sharks',
 'Sitting in the water',
 'Transatlantic Rowing',
 'Bodysurfing',
 'Rowing',
 'Shark fishing',
 'Surfing & filming dolphins',
 'Filming',
 'Swimming after falling overboard',
 'Diving / Filming',
 'Fishing for blue sharks',
 'Standing in inner tube',
 'Body surfing or Boogie boarding',
 'Kayaking ',
 'Feeding fish',
 'Playing with an air mattress',
 'Kite boarding',
 'Shark diving',
 'Petting a shark',
 'Kneeling in the water',
 'Fell into the water',
 'Shark watching',
 'Diving for lobsters',
 'Kite Surfing',
 'Scuba diving / culling lionfish',
 'Kitesurfing',
 'Sailing',
 'Spearfishing / Free diving',
 'Free diving / Photographing pilot whales',
 'Filming a documentary',
 'Attempting to remove fishing net from submerged object',
 'Kiteboarding',
 'Diving for crayfish',
 'Diving ',
 'Swimming / snorkeling',
 'Diving for Abalone',
 'Casting a net',
 'Marathon swimming',
 'Longline fishing for sharks',
 'Wrangling a shark',
 'Attempting to free the shark',
 'Walking in surf',
 'Swimming ',
 'Swimming & snorkeling',
 'Boogie Boarding',
 'Playing in the surf',
 'Fly fishing',
 "Fishing - 'tag & release'",
 'Swimming to shore with floatioon devices after boat engine conked out',
 'Dragging stranded shark into deeper water',
 'Bathing',
 'Bodyboarding',
 'Swimming or boogie boarding',
 'Wading or swimming',
 'Free diving ',
 'Attempting to rescue an injured & beached shark',
 'Free diving / spearfishing',
 'Crayfishing',
 'Diving, feeding sharks',
 'Attempting to Kite surf from Egypt to Saudi Arabia',
 'Fishing (illegally)',
 'Diving, photographing sharks',
 'Wade fishing',
 'Jumping in the waves',
 'Wade Fishing',
 'Standing, collecting sea stars',
 'Floating ',
 'Swimming or Snorkeling',
 'Kayaking or Wave skiing',
 'Jet skiing',
 'Standing or boogie boardin',
 'Kite Boarding',
 'Washing sand off a speared fish',
 'Standing, holding shark pup',
 'Diving / fishing',
 'Wakeboarding',
 'Diving for abalone',
 'Shark fishing on the Ricardo Astorga',
 'Shark fishing on the Don Agust√≠n-VI. ',
 'Attempting to fix motor',
 'Swimming /  Whale Watching',
 'Swimming after boat became disabled',
 'Rescuing',
 'Measuring sharks',
 'Swimming / treading water',
 'Surf fishing / wading',
 'Spearfishing (free diving)',
 'Paddling on kneeboard',
 'Swimming to shore from capsized kayak',
 'Paddle-boarding',
 'Swimming, attempting to rescue a girl  believed to be drowning',
 'Washing his feet',
 'Paddle-surfing',
 'Crawling',
 'Diving, but on the surface when bitten by the shark',
 'Air Disaster',
 'Crabbing',
 'Yacht race',
 'Sinking of the cargo ship Mark Jason',
 'Fishing boat swamped in storm',
 'Swimming, towing surfboard',
 'Swimming or surfing',
 'Rowing an inflatable dinghy',
 'Sea Disaster',
 'Night diving',
 'Free-diving',
 'Walking out of the water after surfing',
 'Fishing from surfski',
 "Accidentally stood on hooked shark's tail before attempting to gut it ",
 'Attempting to chase shark out to sea',
 'Fishing for snapper',
 'Removing fish from a trap',
 'The 426-ton cargo ship Mia, laden with cement, capsized in heavy seas ',
 'Wading?',
 'Jumping',
 'Floating near boat & observing bioluminesce',
 'Jumped into the water',
 'Surf paddling',
 'Murder',
 'Removing hook from shark',
 'Reviving a sedated shark',
 'Shark tagging',
 'Swimming / jumping off a jetty',
 'Playing on a sandbar',
 'Shrimping',
 'Swimming / Body Surfing',
 'Playing soccer in the water',
 'Free diving / modeling',
 'Diving / Kissing the shark',
 'Lifesaving drill',
 'Touching sharks',
 'Competing in the Woodvale Atlantic Rowing Race',
 'Night Surfing',
 'Standing / Surfing',
 'Treading water/ Surfing',
 'Removing shark from net',
 'Boogie boarding, kicked at object in the water',
 'Scuba diving in aquarium tank',
 'Holding onto an inflatable boat',
 'Swimming with boogie board',
 'Spearfishing (Free diving)',
 "Crouching in 2' of water",
 'SCUBA Diving',
 'Diving in aquarium display tank',
 'Attempting to drive shark away from sailing regatta',
 'Fishing from a kayak',
 'Swept out to sea by the tsunami, she clung  to a log for 24 hours',
 'Scurfing (surfboard being  towed behind a boat)',
 'Chumming for white sharks',
 'Spearfishing/ filming',
 'Diving & fishing with net',
 'Wading / fishing & carrying a bag of fish',
 'Fishing for squid aboard the trawler Shikishima-Maru when the shark leapt into the boat',
 'In water with diving seabirds',
 'Swimming, poaching perlemoen',
 'Boogie-boarding / swimming',
 'Free diving & spearfishing',
 'Tandem surfing',
 'Five men on makeshift raft after their 10 m fishing boat  capsized and sank in rough seas. Survivors rescued after  7.5 hours in the water',
 'Surf skiing',
 'Kayaking (returning from spearfishing)',
 'Air disaster. Flash Airlines Boeing 737 crashed into the Red Sea',
 'Swimming / shipwreck',
 'Surfing amid a shoal of sharks',
 'Swimming to shore from boat or kayak',
 'Sitting on surfboard',
 'Wading near a fishing net',
 'Wading to shore from his boat',
 'Standing, stepped on shark',
 'Wade-fishing',
 'Swimming, wearing black wetsuit & swim fins',
 'Walking, carrying surfboard & stepped on shark',
 'Swimming with pod of dolphins',
 'Killing  sharks',
 'Swimming (using a float)',
 'Petting captive sharks',
 'Unknown',
 "Fishing, standing in 2' of water",
 'Fishing from Surfboard',
 'Boogie boarding or Surfing',
 'Wading, when he stepped on the shark',
 'Shark Fishing',
 'Attempting to retreive a dinghy',
 'Snorkeling (filming the sardine run)',
 'Floating on a raft',
 'Fishing, removing the shark from his line',
 'Playing in the surf with his 2 dogs',
 'Collecting beche-de-mer',
 'Fishing from prawn trawler',
 'Scallop diving (using surface-supplied air & a POD) ',
 'Fishing (Drowned 2-Apr-2002)',
 'Surfing, but standing in water alongside board',
 'Body-boarding',
 'Swimming /  boogie boarding',
 'Capsized fishing boat',
 'Kite-Boarding',
 'Surfing, fell off surfboard & stepped on the shark.',
 'Wreck / Technical diving',
 'Walking in shallows',
 'Fell off banana boat',
 'Floating face-down in knee-deep water',
 'Hiking on the beach',
 'Spearfishing, carrying his catch',
 'Standing alongside surfboard',
 'Batin',
 'Attempting to catch a crocodile',
 "Sinking of the 40' Esperanza off St. Maartin with 36 refugees on board",
 'Fishing for whiting',
 'Swimming back from anchored sailboat',
 'Diving for sea urchins',
 'Diving (shell maintenance)',
 'Shipwrecked',
 'Fell onto dead shark',
 'Standing / surfing',
 'Swimming / Body surfing',
 'Conducting research',
 'Swimming out to porpoises ',
 'Windsurfing, but sitting on his board',
 'Surfing / Wading',
 'Attempting to illegally enter the USA',
 'Spearfishing, holding mesh bag with speared fish',
 'Air Disaster - Piper aircraft crashed into the sea, killing all on board',
 'Boogie boarding / wading',
 'Feeding prawns to captive sharks',
 'Canoe with 3 men onboard sank',
 'Fishing for tarpon',
 'Surfing (sitting on his board)',
 'Spearfishing, but swimming at surface',
 'Surfing, lying on surfboard',
 'Wading to shore after surfing',
 'Wading with surfboard',
 "Lying prone in 2' of water",
 'Spearfishing & holding catch',
 'Swimming with dolphins',
 'Wading in school of baitfish',
 'Adrift in a life jacket',
 'Splashing / wading',
 'Swimming after being swept into sea by a large wave',
 'Spearfishing & diving for paua',
 "Scientific research (Dr. Sonny Gruber's student)",
 'Swimming, towing a kayak',
 'Body surfing or body boarding',
 'Swimming near pod of whales',
 'Cruising',
 'Paddle Skiing',
 'Inflatable boat',
 'Splashing',
 'Fishing for tuna',
 'Fishing / washing bait off hands',
 'Moving a shark in a net ',
 'Surfing (or body boarding)',
 'Free diving for abalone',
 'Swimming / surfing',
 'Towing rubber dinghy',
 'Surfing (lying prone on his board)',
 'Snorkeling \x96 hunting crayfish and abalone',
 'Swimming or paddle boarding',
 'Spearfishing on scuba & transferring fish onto a stringer',
 'Scuba diving (submerged riding a scooter)',
 'Body boarding or surfing',
 'Fishingat',
 'Walking / surfing',
 'SCUBA diving',
 'Floating on raft',
 'Wading / Surfing',
 'Fishing for octopus',
 'Spearfishing / night diving',
 'Body surfing, stood up on sandbar',
 'Rowing ',
 'Watching seals',
 'Attempting to attract dolphins',
 'Swimming or snorkeling',
 'Surfing / Swimming',
 'Free diving with a pod of dolphins',
 'Tech diving ',
 'Shell Diving',
 'Swimming breast stoke',
 'Fishing in knee-deep water',
 'Dived naked into the water on a bet',
 'Swimming in fish tank',
 'Boeing 757 enroute from Porta Plata plunged into the sea',
 'Swimming with mask & snorkel',
 'Chumming for sharks',
 'Diving, gathering shellfish',
 'Fell off aircraft carrier',
 'Playing / standing',
 'Abalone diving using Hookah (near calving whales)',
 'Abalone diving using Hookah (resting on the surface)',
 'On a float',
 '"Riding waves on a board"',
 'Jumped off surfboard & landed on the shark',
 'Scuba diving (ascending using scooter)',
 'Playing / jumping',
 'Sleeping in anchored boat',
 'Scuba diving for bivalves',
 'Wind surfing',
 'Surfing, sitting on board',
 'Murder victim',
 'Commercial diver (submerged or treading water)',
 'Surfing, paddling seawards',
 'Adrift on refugee raft',
 'Jumped off rocks into white water',
 'Freediving for seashells',
 'Swimming alongside NOAA research vessel Discoverer',
 'Removing shark from tank in nightclub ',
 'Swimming, after falling off towed kneeboard',
 'Playing volleyball with friends',
 'Hookah diving',
 'Surfing, paddling shorewards',
 'Stamding',
 'Watching the shark feeding on a dead pinniped',
 'Riding floatation device',
 'Free diving for abalone (ascending)',
 'Fishing for lobsters',
 'Oyster fishing',
 'Paddling on surfboard or body board',
 'Scuba diving at seal colony',
 'Floating on his back',
 'Paddling on surfboard',
 'Free diving & spearfishing (ascending)',
 '   ',
 'Standing in waist-deep water, helping his father tend a gill net containing dead fish',
 'Lying on surfboard',
 'Spearfishing / free diving',
 'Scuba diving (submerged)',
 'Hookah diving for sea urchins',
 'Snorkeling, carrying a speared fish in her hand',
 'Fell from cliff while fishing & disappeared in strong current',
 'Fisherman',
 "Zosimo & his son, Jeffrey Popa, failed to return from overnight fishing trip in a 14' boat, Boat apparently sank, debris recovered but his son & boat were never found",
 'Preparing to fish for jack-mackerel',
 'Scuba diving ',
 'Scuba diving & filming',
 'Hookah diving for pen shells ',
 'Fishing for yellowtail, Seriola quinqueradiata',
 'Diving for pen shells',
 'Fishing from rocks, swept out to sea by large wave & treading water',
 'Finning the shark that bit him',
 'Swimming from makeshift raft  to life vest after fishing boat sank',
 'Swimming behind sailboat',
 'Surfing, collided with shark',
 'Surfing (or sailboarding)',
 'Scuba diving (but on surface)',
 'Free diving / spearfishing, from paddleboard & floating on the surface',
 'Snorkeling, possibly holding a fish',
 'Resting on surfboard',
 'Lying on surfboard & paddling',
 'Free diving for trochus',
 'Scuba diving & spearfishing',
 'Board sailing',
 "On board 51' fishing vessel One Ki",
 'Wading, knocked down & swept away by large waves',
 'Swimming in canal',
 "Fishing, stepped on hooked shark's head",
 'Observing a shark feeding on a carcass of a humpback whale',
 'Hookah diving for abalone (descending)',
 "Filming 5' blue shark",
 'Playing ',
 "Fell off surfboard 20' from shore",
 'Windsurfing (urinating on his board)',
 'Scuba diving, but swimming on surface',
 'Swimming in strong current with 3 others when he disappeared',
 'Surfing with dolphins',
 'Scuba diving, hand feeding sharks',
 'Spearfishing using scuba & trailing a string of bleeding fish',
 'Skindiving',
 'The Christie V sank on 11/6/1988, survivors were adrift on a dinghy',
 'The MV Dona Marilyn sank in Typhoon Unsang with the loss of 389 lives',
 "Diving in Sharkey's Reef restaurant\x92s aquarium",
 'Free diving & spearfishing ',
 'Spearfishing on scuba',
 'Sittting in water with his child',
 'Shell diving',
 'Surfing / treading water',
 'p√™cheur de bichiques',
 "Onboard 21' powerboat that capsized in rough seas",
 'Standing ',
 'Lying atop surfboard',
 'Drift fishing',
 'Fell overboard  from the Taiwanese fishing trawler Lien Cheng Feu ',
 "Attempting to lasso shark's tail",
 'Returning to shore, collided with shark',
 'Ferry boat Dona Paz with 4431 passengers exploded & caught fire when she collided with an  oil tanker ',
 'Vessel caught fire & capsized, survivors in the water',
 'Scuba Diving for scallops',
 'Dropping anchor',
 'Swimming from shore to anchored sailboat',
 'The inter-island ferry Vula sank in heavy weather',
 'Jumped into the water from a cliff',
 'Boat',
 'Adrift after ditching plane in the sea',
 'Free diving  & spearfishing (submerged)',
 'NSB Meshing',
 'Racing ski',
 'Fishing, fell from rocks & disappeared',
 'Hookah diving for abalone',
 'Floating on inner tube after diving for lobster',
 'Free diving & spearfishing (descending)',
 'Bottom fishing for lingcod & had hooked a fish',
 'Playing in knee-deep water',
 'Surfing, but lying prone on his board',
 'Free diving for scallops',
 'Scuba Diving for lobster (at surface)',
 'Investigating shark sighting',
 'Sailing on catamaran & fell into the water',
 'Surfing or body surfing',
 'Free diving , but surfacing',
 'Boat capsized?',
 'Sea disaster, foundering of the cargo vessle M/V Dorolonda',
 "During a shark fishing tournament, the 18' Boatem was capsized by waves, throwing 3 men into the water ",
 'Towing her sister on plastic ski board',
 'Steinhart Aquarium',
 'Scuba diving for abalone',
 'Ferry boat sank',
 'Swimming from the New Venture ',
 '14 m prawn trawler New Venture capsized  & sank in heavy seas Three people in the water',
 'Floating on air mattress',
 'Surfing & dangling foot in water amid baitfish',
 'Water-skiing',
 'Paddleskiing',
 'Ran into the water',
 'In waist-deep water',
 'Free diving for abalone from Zodiac (submerged)',
 'Paddle Boarding',
 'Spearfishing ',
 'Sailboarding, fell into water 100 yards outside the breakwater',
 'Fishing on a boat',
 'Spearfishing, but swimming on surface',
 'Inspecting teeth of supposedly dead (hooked & shot) shark',
 "Diving to untangle a crab trap line from boat's propeller",
 "16' catamaran capsized previous night, occupants stayed with wreckage until morning, then attempted to swim ashore",
 'Snorkeling on surface',
 'Catching sardines',
 'Scuba diving, reportedly also spearfishing',
 'Foundering of the Israeli freighter Mezada',
 'Standing / Wading',
 'Free diving Spearfishing',
 'Exercising his dog in the shallows',
 'Commercial spearfishing',
 'Free diving / spearfishing, ',
 'Diving in tuna net',
 'Resting on body board',
 'Skin diving',
 'Sinking of the ferryboat Don Juan',
 'Sinking of the ferryboat Bongbong 1',
 'Hookah Diving',
 'Gaffing netted shark',
 'Freedom swimming',
 'Murdered by Thai pirates',
 'Floating with life preserver after his boat foundered',
 'Floating on inner tube raft',
 "Explosion destroyed 28' boat, survivors in the water ",
 'Fishing for mackerel',
 'Swimming, after single-engine aircraft went down in the sea',
 'Fishing for bottom fish',
 'Floating on an inflatable raft',
 'Free diving for abalone (surfacing)',
 "40' fishing boat sank",
 'Spearfishing / Scuba diving',
 'Collecting fish from net',
 'Fishing for yellowtail',
 'Their 9 m launch was run down by a 25,000-ton Japanese freighter  on the night of 3-11-1977 & they drifted, clinging to an icebox for 2 days',
 "Pushed surfmat of a young girl out of the shark's path, drawing shark's attention to his own board",
 'Hookah diving for abalone (submerged)',
 'Thrashing the water / imitating the shark victim from "Jaws"',
 'Fishing for white shark',
 'Shipwreck',
 'Skindiving,',
 '3,909-ton Panamanian freighter Chieh Lee sank in a typhoon',
 'Surfing, fell off surfboard',
 "Sitting in bow of her father's 5 m boat",
 'Competing in a light tackle game fishing',
 'Fishing for snoek & yellowtail',
 'Spearfishing / scuba diving',
 'Attempting to drive shark away from the beach',
 'Filming & feeding captive sharks',
 'Floating on a small orange raft ',
 'Scuba diving for abalone (at surface)',
 'Swimming near his boat',
 'Spearfishing Competition',
 'Floating in inner tube',
 'Diving & force-feeding the shark',
 'Attempting to drag hooked shark ashore by its tail',
 'Ferry capsized',
 'Swimming underwater from crayfish cage to a fishing bait',
 '3.3 m fishing boat sank. Treveluwe & Peter Hodgson (wearing lifejackets) were drifting in the current',
 'Freedom Swimming',
 'Free diving for abalone (submerged)',
 'Adrift after the sinking of the motor yacht Princess Dianne',
 'Free diving (but on surface)',
 'Fishing boat swamped in a storm',
 'Fishing for kob',
 'Fishing for red fish',
 'Sitting',
 'Swimming alongside yacht Mexico Fiesta',
 'Being pulled to shore from wreck of 25-ton fishing vessel Alan S',
 'Free diving, Spearfishing',
 'Crabbing (spearing crabs)',
 'Fishing from paddleski',
 'Scuba diving & U/W photography',
 'Sitting in shallows',
 'Free diving, collecting shells',
 'Scuba diving & feeding fish',
 'Hookah diving (submerged)',
 'Wreck of the 1689-ton Portuguese  coaster Angoche',
 'Fishing for prawns',
 'Sea Disaster Sinking of ferryboat Christina',
 'Motor launch Baby Princesa capsized with 22 people on board',
 'Freediving',
 'Air disaster',
 'Attempted to return injured shark to the sea',
 'Spearfishing / freediving',
 'Washing cooking pans',
 'Washing clothes on stairs',
 'Fishing, trying to catch the end of his fishing line',
 'Scuba diving for lobsters',
 'Freediving for abalone (at surface)',
 'Surf-fishing',
 'Netting pilchards',
 'Hard hat diving',
 'Sight-seeing',
 'Feeding mullet to sharks',
 'Wreck of the Storm King',
 'Spearfishing using Scuba',
 'Sinking of the ferryboat Dumaguete ',
 'Playing with a frisbee in the shallows',
 'Leaving the water',
 'Dynamite fishing',
 'Small boat with 2 men onboard hit a submerged coral formation. Men began swimming to shore',
 'Clamming',
 'Schooner sank during a storm',
 'Diving. Shark \x93swallowed\x92 his hand, so he threw his other around the shark and went \x93shark-back riding\x94 for 30 yards until the shark opened its jaws',
 'Wading & pushing dinghy toward  the shallows',
 'Picking up shark by the tail',
 'Swimming after his canoe capsized',
 'Sinking of the M/V Mindoro during a typhoon',
 'Standing on sandbar',
 "Boat capsized between O'ahu & Molokai",
 'Pulling shark from the water',

Tras analizar los valores de "activity", establecemos las siguientes categor√≠as y coincidencias b√°sicas para cada categor√≠a:

    - Surfing = todo lo que contenga "surf", "wave" o "board" (todo lo que sea con una tabla o relacionado con las olas, sin distinguir entre disciplinas o tipos de surf).
    
    - Swimming = todo lo que contenga "swim" o "snorkel".
    
    - Diving = todo lo que contenga "diving" (sin distinguir el tipo de buceo).
    
    - Fishing = todo lo que contenga "fish".
       
    - Shark Activities = todo lo que contenga "sharks" (relacionado con los tiburones).
    
    - Saling = todo lo que contenga "boat", "ship", "ferry", "raft", "rowing", "paddling", "kayak", "sail" (sin distinguir entre tipos de embarcaciones).

Generaremos primero estas 5 categor√≠as b√°sicas agrupadas y valoraremos la situaci√≥n despu√©s de hacerlo.

El orden de ejecutar el .replace ser√° importante ya que algunos valores comparten palabras clave de distintas categor√≠as ("swim" y "fish", por ejemplo) y el replace definitivo ser√° el primero que se ejecute.

Definimos una funci√≥n (activities) para hacer lo que queremos conseguir. Lo ideal ser√≠a definirlas en el archivo "src" e importarlas para poder utilizarlas, pero para entender mejor el proceso se presenta la definici√≥n de las funciones en este mismo archivo.

In [25]:
def activities (i): # Para entender
    if 'surf' in str(i).lower():
        return 'surfing'
    
    elif "wave" in str(i).lower():
        return 'surfing'
    
    elif "board" in str(i).lower():
        return 'surfing'
    
    
    elif "swim" in str(i).lower():
        return 'swimming'
    
    elif "snorkel" in str(i).lower():
        return 'swimming'
    
    elif "bath" in str(i).lower():
        return 'swimming'
    
    
    elif "diving" in str(i).lower():
        return 'diving'
    
    
    elif "fish" in str(i).lower():
        return 'fishing'
    
    
    elif "shark" in str(i).lower():
        return 'shark_activities'
    
    
    elif "boat" in str(i).lower():
        return 'sailing'
    
    elif "ship" in str(i).lower():
        return 'sailing'
    
    elif "ferry" in str(i).lower():
        return 'sailing'
    
    elif "raft" in str(i).lower():
        return 'sailing'
    
    elif "rowing" in str(i).lower():
        return 'sailing'
    
    elif "paddling" in str(i).lower():
        return 'sailing'
    
    elif "kayak" in str(i).lower():
        return 'sailing'
    
    elif "sail" in str(i).lower():
        return 'sailing'
    
    
    else:
        return str(i).lower()

In [26]:
attacks["activity"] = attacks["activity"].apply(activities)

Observamos como la cantidad de valores √∫nicos se ha reducido a menos de un cuarto (hemos limpiado casi 1.200 valores √∫nicos asign√°ndolos a una nueva categor√≠a), lo cual supone un avance importante en la limpieza de los datos de la columna "activity".

In [27]:
len(list(attacks.activity.unique()))

353

In [29]:
attacks.activity.unique() # Observamos los valores √∫nicos restantes.

array(['sailing', 'standing', 'surfing', 'diving', 'swimming', 'fishing',
       'walking', 'shark_activities', 'paddle-skiing', 'wading',
       'unknown', 'canoeing', 'sup', 'photo shoot', 'kakaying',
       'washing hands', 'floating', 'lobstering', 'floating in tube',
       'feeding stingrays?', 'sea disaster', 'treading water',
       'playing in the water', 'playing', 'sitting in the water',
       'filming', 'standing in inner tube',
       'playing with an air mattress', 'kneeling in the water',
       'fell into the water', 'filming a documentary', 'casting a net',
       'standing, collecting sea stars', 'floating ', 'jet skiing',
       'attempting to fix motor', 'rescuing', 'washing his feet',
       'crawling', 'air disaster', 'crabbing', 'yacht race', 'wading?',
       'jumping', 'jumped into the water', 'murder',
       'playing on a sandbar', 'shrimping', 'playing soccer in the water',
       'lifesaving drill', "crouching in 2' of water",
       'swept out to sea by the tsunami, she clung  to a log for 24 hours',
       'air disaster. flash airlines boeing 737 crashed into the red sea',
       'attempting to retreive a dinghy', 'collecting beche-de-mer',
       'walking in shallows', 'floating face-down in knee-deep water',
       'hiking on the beach', 'batin', 'attempting to catch a crocodile',
       'conducting research', 'attempting to illegally enter the usa',
       "lying prone in 2' of water", 'adrift in a life jacket',
       'splashing / wading',
       "scientific research (dr. sonny gruber's student)", 'cruising',
       'paddle skiing', 'splashing', 'towing rubber dinghy',
       'watching seals', 'attempting to attract dolphins',
       'dived naked into the water on a bet',
       'boeing 757 enroute from porta plata plunged into the sea',
       'playing / standing', 'on a float', 'playing / jumping',
       'murder victim', 'commercial diver (submerged or treading water)',
       'jumped off rocks into white water',
       'playing volleyball with friends', 'stamding',
       'riding floatation device', 'floating on his back', '   ',
       'playing ',
       'the christie v sank on 11/6/1988, survivors were adrift on a dinghy',
       'the mv dona marilyn sank in typhoon unsang with the loss of 389 lives',
       'sittting in water with his child', 'p√™cheur de bichiques',
       'standing ',
       'vessel caught fire & capsized, survivors in the water',
       'dropping anchor', 'jumped into the water from a cliff',
       'adrift after ditching plane in the sea', 'nsb meshing',
       'racing ski', 'playing in knee-deep water',
       'sea disaster, foundering of the cargo vessle m/v dorolonda',
       'steinhart aquarium',
       '14 m prawn trawler new venture capsized  & sank in heavy seas three people in the water',
       'floating on air mattress', 'water-skiing', 'paddleskiing',
       'ran into the water', 'in waist-deep water', 'catching sardines',
       'foundering of the israeli freighter mezada', 'standing / wading',
       'exercising his dog in the shallows', 'murdered by thai pirates',
       'their 9 m launch was run down by a 25,000-ton japanese freighter  on the night of 3-11-1977 & they drifted, clinging to an icebox for 2 days',
       '3,909-ton panamanian freighter chieh lee sank in a typhoon',
       'floating in inner tube',
       'adrift after the sinking of the motor yacht princess dianne',
       'sitting', 'crabbing (spearing crabs)', 'sitting in shallows',
       'wreck of the 1689-ton portuguese  coaster angoche',
       'washing cooking pans', 'washing clothes on stairs',
       'netting pilchards', 'sight-seeing', 'wreck of the storm king',
       'playing with a frisbee in the shallows', 'leaving the water',
       'clamming', 'schooner sank during a storm',
       'wading & pushing dinghy toward  the shallows',
       'sinking of the m/v mindoro during a typhoon',
       'standing on sandbar', 'beach seine netting',
       'vehicle plunged over cliff into the water',
       'sinking of the dredge world atlas', 'overturned skiff',
       'colombian  (avianca) dc-4 airliner plunged into the sea 5 minutes after takeoff',
       'argentine air force c-54', 'arsinoe, a french tanker',
       'walking on reef', 'dangling feet in the water',
       'collecting marine specimens', 'standing in waist-deep water',
       'filming underwater, carrying powerhead',
       'floating on his back in an inner tube',
       'searching for remains of  dr. marais',
       'conducting a promotional film project for the gemini space program (a practice astronaut recovery)',
       'canoe capsized with 10 occupants, 8 survived,  hamilton swam off to seek help',
       'lying in 2 feet of water',
       'treading water while alongside capsized yacht',
       'seining for bait, standing in chest-deep water',
       'washed into sea while picking opihi',
       'the 500-ton coastal trader polurrian foundered ',
       'dived from inner-tube',
       'u.s. airforce crewman reported missing after bailing out of jet',
       'escaping from alacatraz', 'washing',
       '25-foot cabin cruiser happy jack sank in heavy seas',
       'splashing ', 'gathering shells', 'attaching a line at sea',
       'walking in chest-deep water', 'floating on back',
       'cleaning a tank', 'collecting aquarium specimens',
       'pacific seafarer of us navy', 'ocean racing',
       'hand lining for shad', 'collecting shells',
       'air disaster: crash of air france super constellation ',
       'standing in knee-deep water',
       'testing classified underwater electronic gear for raytheon corporation, vessel torn apart by explosion',
       's2f-1 airplane crashed immediately after carrier take-off',
       'standing, watching seine netters',
       'dived from dinghy to retrieve oar in heavy seas',
       'standing in chest-deep water',
       "adrift, hanging onto cushion, after his 17' skiff ran out of gas & capsized 3 miles from shore",
       'gigging for flounder', 'pulling anchor',
       'columbian petrol barge rio atrato burned and sank',
       'working prawn net', 'dragging banana seeds through the shallows',
       'm.v. tropical sank. sole survivor rode oil drums for 8 days without food or water.',
       '3 men & 2 boys picked up wearing life jackets and with inner tube',
       'air/sea disaster',
       'attempting to set underwater endurance record', 'hunting turtle',
       "competing in u/w endurance record, standing beside drum in 10' of water",
       'hunting lobsters in 2.4 m of water',
       'crossing the bay at the ford',
       'american freighter mormackite, bound from buenos aires for baltimore, capsized & sank in heavy seas',
       'crouching in the water', 'aircaft exploded',
       'body found on deserted luxury yacht, 38\x92 christine',
       'swept off deck of s.s.frontenac enroute from west indies to us',
       'survived crash of two-engine  c-46 transport plane carrying 62 migrant workers from puerto rico to usa ',
       'suicide', 'sitting on side of dinghy mending a net',
       'defecating in water beneath the docks', 'bending over',
       "lying on the bottom of a 16' dinghy", 'no details',
       'lifesaving exhibition', 'leicester abandoned in a hurricane',
       'underwater photography', 'jumping in swells',
       'american cruiser indianapolis torpedoed & sunk by the japanese submarine i-58',
       '90 european civilians, many women & children, were placed on the deck of a japanese submarine that submerged when it was well offshore',
       'playing on rock, slipped & fell into the water',
       'uss gambier bay cve-73  shelled & sunk  at 09h57 on 10/24/1944, by japanes fleet enroute to attack the allied landing force at leyte.',
       'parachuted into pacific',
       'the cuban freighter libertad was torpedoed and sunk by the german submarine u-129',
       'the 6711-ton american freighter & troop transport cape san juan was torpedoed by the japanese submarine i-21',
       's2n navy scout plane went down, e.h. almond & lieut a.g. reading in water',
       'the 3540-ton alfonso penna was torpedoed & sunk by the italian submarine barbarigo',
       'known as the battle of the bismarck sea :  8 japanese destroyers guarding a convoy of 8 transports were attacked by 129 allied fighters, 207 bombers & 3 squadrons of the royal australian air force. ',
       'the uss wahoo torpedoes & sank the japanese troop transport buyo maru',
       'thrown from destroyer when shell hit',
       'explosion & sinking of the uss juneau after being torpedoed by the submarine  i-85',
       'in rubber dinghy with captain eddie rickenbacker for 21 days. ',
       'the ss potlach was torpedoed & sunk by the u-153 on 27-jun-1942. ',
       'sculling',
       'h.m.s. cornwall & h.m.s.dorsetshire sunk by japanese dive bombers. officers & men in the water formed a circle with 60 of their dead in the center for 36 hours',
       'esso bolivar was torpedoed & shelled by the german submarine u-126',
       "days before the surrender of singapore, the 3 men escaped to sumatra where they acquired a 17' dinghy. after 125 days at sea they drifted back to sumatra",
       'torpedoed & burning british  light cruiser with a crew of 450 men',
       'hmas parramatta torpedoed & sunk by the u-559',
       'british cruiser dunedin torpedoed & sunk by the u-124',
       'german raider kormoran was sunk in an engagement with hmas sydney',
       'ss ethel skakel foundered in central america hurricane of 1941',
       'seine netting', 'slipped off rocks and fell into the water',
       'standing on sandbank', 'dived into the water', 'male',
       'standing in water with child in her arms',
       'japanese freighter bokuyo maru burned & sank', 'dived for a coin',
       'scooping prawns',
       'the schooner elizabeth, bound from bluefields, nicaragua to the river port of san carlos foundered',
       'tzenny chandris, a greek freighter laden with scrap iron, foundered in heavy weather',
       'wreck of a sampam',
       'disappeared 11 days earlier, probable homicide victim',
       'taken as he dived into the water',
       'dived into sea from launch & bitten immediately',
       'splashing in water ', "sitting in 3' of water",
       'yacht of michael howell capsized', 'standing on his hands',
       'catching a turtle',
       'on expedition filming a feature movie & standing on tripod',
       'sea disaster, wreck of the  ss norwich city',
       'fell from wharf into water & attacked immediately',
       'sea disaster, sinking of the  ss vestris',
       'retrieving meat from a cage in the water',
       'italian liner principessa mafalda sank',
       'riding horseback across the creek',
       'standing, collecting bananas',
       'attempting to rescue drowning man', 'jumped out of canoe',
       'inebriated, woke from sleep and fell off deck into the water ',
       'floating, after falling or jumping off the standard oil tanker frederick w. weller',
       'dry shelling', 'seaplane columbus ditched in the sea',
       "fell from his father's back into the water",
       'wading to dinghy, carrying his son',
       'the coastwise steamer san basilio capsized in a typhoon',
       'floating face down', 'knocked into the water', 'cutter capsized',
       'wading (shrimping)', 'wreck of the tug magellan',
       'taking wife to beach & about 1 m from the shore',
       'netting shrimp', 'washing clothes', 'hauling in net',
       '3-masted steel barque glenbank foundered during a cyclone',
       'on december 28, 1908, an earthquake, followed by tsunamis, destroyed coastal towns in silcily and southern italy, killing more than 100,000 people',
       'fell from the jetty',
       'the 168-ton belmore foundered in heavy seas',
       'the british steamer caribbee foundered', '.', 'floating in creek',
       'the schooner tahitienne foundered in a hurricane',
       'washing horses', 'floating or standing', 'harpooning turtles',
       'catching crabs', 'hunting seashells', ' ',
       'standing, gathering oysters',
       'the cutter francis adams foundered', 'sponge divers',
       'trailing hand in the water', 'loss of the schooner nomad',
       'angling', 'hunting seals',
       'sea disaster : wreck of the carrie e. long',
       '"crossing the river"', 'a barque wrecked',
       'hms victoria collided with the hms camperdown', 'canoe swamped',
       'his balloon crashed in the harbor', 'murdered', 'riding a horse',
       ' a canoe was pursuing a schooner that had forcibily abducted 5 young girls',
       'sea disaster, canoes capsized in storm', 'fleeing across a river',
       'treading for clams', 'parachuted from balloon',
       'working on the bridge when he fell into the river',
       'probabable drowning', 'the dwarka foundered',
       'the cutter yacht cutty sark sank', 'crossing the river mouth',
       'sea disaster, wreck of the alfred watts',
       'sea disaster, wreck of the sloop sara', 'oystering',
       'sea disaster : wreck of the taiaroa',
       'wreck of the schooner pohoiki ', 'yachting accident',
       'floating, holding onto an oar after dory capsized',
       'floating with life buoy after pilot launch capsized',
       'escaping from blackbirding vessel',
       'burning of the s.s. missouri', 'wreck of the 150-ton brig maria',
       'a junk foundered', 'wreck of the aphrodite',
       'coming ashore on a hawser', 'reaching for life preserver',
       'trying to catch a wounded bird', 'deserting the bark nazarene',
       '43-ton schooner irene capsized & sank',
       'vessel capsized, wading ashore carrying an oar', 'hilo',
       'wreck of the sovereign', 'wreck of the tweed',
       'wreck of the uss somers', 'jumped into river',
       'unknown, but it was said to be the "first known attack in sydney harbour"',
       'hooking into a whale', 'american schooner orator capsized  ',
       'washing a dog', 'wreck of the schooner driver',
       'hbm magpie foundered in a squall', 'conch diver',
       'washing himself', 'ascending from a dive',
       'washing his pig in preparation for a religious ceremony',
       'a dhow capsized', 'yachtsman in a zodiac',
       'lashing logs together when he fell into the water',
       'standing, washing rear wheels of his ambulance in ankle-deep water',
       'spent 8 days in dinghy'], dtype=object)

Como podemos observar, el resto de actividades son muy variadas y no tiene demasiado sentido clasificarlas en grupos de actividades.

Tras valorar la situaci√≥n, decidimos incluir todos estos valores en una nueva categor√≠a llamada "other" que englobe a todas las actividades no inclu√≠das en las otras categor√≠as b√°sicas.

Volvemos a definir la funci√≥n activities() incluyendo esta nueva consideraci√≥n:

In [30]:
def activities (i):
    if 'surf' in str(i).lower():
        return 'surfing'
    
    elif "wave" in str(i).lower():
        return 'surfing'
    
    elif "board" in str(i).lower():
        return 'surfing'
    
    
    elif "swim" in str(i).lower():
        return 'swimming'
    
    elif "snorkel" in str(i).lower():
        return 'swimming'
    
    elif "bath" in str(i).lower():
        return 'swimming'
    
    
    elif "diving" in str(i).lower():
        return 'diving'
    
    
    elif "fish" in str(i).lower():
        return 'fishing'
    
    
    elif "shark" in str(i).lower():
        return 'shark_activities'
    
    
    elif "boat" in str(i).lower():
        return 'sailing'
    
    elif "ship" in str(i).lower():
        return 'sailing'
    
    elif "ferry" in str(i).lower():
        return 'sailing'
    
    elif "raft" in str(i).lower():
        return 'sailing'
    
    elif "rowing" in str(i).lower():
        return 'sailing'
    
    elif "paddling" in str(i).lower():
        return 'sailing'
    
    elif "kayak" in str(i).lower():
        return 'sailing'
    
    elif "sail" in str(i).lower():
        return 'sailing'
    
    
    else:
        return "other"
    
    
# Podemos volver a ejecutar la funci√≥n completa porque, seg√∫n los condicionales establecidos, todo se mantendr√° igual salvo aquellos que no coincidan con alguna de las categor√≠a previamente definidas (si esto ocurre se sustituir√° por "other").

In [31]:
attacks["activity"] = attacks["activity"].apply(activities)

Observamos como ya no existen valores que no coincidan con una de las 6 categor√≠as previamente definidas.

In [32]:
len(list(attacks.activity.unique()))

7

In [33]:
attacks.activity.unique()

array(['sailing', 'other', 'surfing', 'diving', 'swimming', 'fishing',
       'shark_activities'], dtype=object)

Ya tenemos los datos de la columna "activity" preparados para poder trabajar con ellos y comprobar nuestra primera hip√≥tesis.

  
  
  7. Procedemos a limpiar la columna **"fatal_y/n"**

Nos damos cuenta de que el caracter "/" da problemas a la hora de trabajar con el nombre de la columna.

Cambiamos el nombre para arreglarlo:

In [35]:
rename = {"fatal_y/n" : "fatal_y_or_n"}

attacks.rename(columns = rename, inplace=True)

In [36]:
attacks.sample()

,case_number,date,year,type,country,area,location,activity,name,sex,age,injury,fatal_y_or_n,time,species,investigator_or_source,pdf,href_formula,href,original_order
3493,1967.12.21.R,Reported 21-Dec-1967,1967.0,Invalid,PAPUA NEW GUINEA,Central Province,Port Moresby,fishing,Bob Valentine,M,32,No injury,NaN,NaN,Questionable incident,H.D. Baldridge (1994),1967.12.21.R-Valentine.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2810.0

Extraemos los valores √∫nicos en esta columna y observamos que existen diferentes posibles valores (y entre ellos valores NaN). 

Procedemos a arreglar este problema:

In [37]:
list(attacks.fatal_y_or_n.unique())

['N', 'Y', nan, 'M', 'UNKNOWN', '2017', ' N', 'N ', 'y']

Primero procedemos a estandarizar los values con errores de escritura a "N" o "Y".

In [38]:
def standar (i):
    if 'N' in str(i).upper() and "UNKNOWN" not in str(i).upper() and "NAN" not in str(i).upper():
        return 'N'
    
    elif 'Y' in str(i).upper():
        return "Y"
    
    else:
        return str(i).upper()

In [39]:
attacks["fatal_y_or_n"] = attacks["fatal_y_or_n"].apply(standar)

Extraemos los valores √∫nicos que tenemos ahora:

In [40]:
list(attacks.fatal_y_or_n.unique())

['N', 'Y', 'NAN', 'M', 'UNKNOWN', '2017']

Hemos resucido los valores √∫nicos al corregir los errores de escritura.

Ahora tenemos los siguientes inconvenientes:

    - Existe al menos un valor "2017" y otro valor "M".
    
    - Los valores NaN son ahora "NAN" por la ejecuci√≥n de la funci√≥n anterior. Esto puede ser un inconveniente, pero como vamos a querer sustituirlos por otro valor, esto no deber√≠a influir en la limpieza (esto en realidad ha sido un error en la funci√≥n, pero trataremos de seguir trabajando a pesar de ello (tambi√©n podr√≠amos volver a ejecutar el c√≥digo)).

Comprobamos la cantidad de datos que existen para cada valor:

In [41]:
attacks["fatal_y_or_n"].value_counts()

N          4301
Y          1389
NAN         539
UNKNOWN      71
M             1
2017          1
Name: fatal_y_or_n, dtype: int64

Como solo existe un "2017" y un "M", decidimos incluirlos en "UNKNOWN" (podr√≠amos deducir que "M" se refiere a "N", pero al ser un √∫nico valor quiz√° sea mejor no tener esto en cuenta y tratar de evitar interpretaciones personales).

In [42]:
def unknown (i):
    if i == "M":
        return "UNKNOWN"
    elif i == "2017":
        return "UNKNOWN"
    else:
        return i

In [43]:
attacks["fatal_y_or_n"] = attacks["fatal_y_or_n"].apply(unknown)

In [44]:
list(attacks.fatal_y_or_n.unique())

['N', 'Y', 'NAN', 'UNKNOWN']

In [45]:
attacks.to_csv("data/attacks_clean2.csv", index=False) # Exportamos el DataFrame para actualizar los datos con los avances de limpieza.

In [46]:
attacks = attacks = pd.read_csv("data/attacks_clean2.csv",encoding='UTF-8')

Ahora ya solo nos queda el problema de los "NAN".

En esta columna solo hay dos posibles valores: fatal attack = yes (Y) o fatal attack = no (N).

No tiene sentido rellenar estos valores nulos con "Y" o "N" seg√∫n lo consideremos. Sin embargo, nos damos cuenta de que en todos aquellos registros en los que el valor de la columna "injury" contiene "fatal", la columna "fatal_y_or_n" contiene el valor "Y". Este es el √∫nico criterio que podemos seguir, ya que no podemos entrar a valorar la gravedad del ataque seg√∫n la informaci√≥n recogida en "injury".

Decisi√≥n --> rellenar los NaN con:
   - "Y" si el valor de "injury" contiene "fatal".
   - "UNKNOWN" si el valor de "injury" no contiene "fatal".

In [47]:
attacks["fatal_y_or_n"].value_counts()

N          4301
Y          1389
NAN         539
UNKNOWN      73
Name: fatal_y_or_n, dtype: int64

In [48]:
for i,row in attacks.iterrows(): # Muy interesante .iterrows() para ir iterando por todas los valores de cada fila.
    if ("fatal" in str(row["injury"]).lower()) & (row["fatal_y_or_n"]=="NAN"): # Si se cumplen las dos condiciones que queremos ("injury" contiene "fatal" y "fatal_y_or_n" es igual a "NAN")
        attacks.loc[i, "fatal_y_or_n" ] = "Y" # Sustituimos el valor en "fatal_y_or_n" ("NAN") por "Y" (esta sintaxis la hemos obtenido a trav√©s las sugerencias que nos daban en un error que hemos obtenido previamente).
        
    else:
        pass # Si las condiciones no se cumplen queremos que todo se mantenga como est√°.

Observamos como la cantidad de "NAN" ha reducido. Esto indica que hemos conseguido lo que quer√≠amos (sustituir los valores "NAN" por "Y" si la columna "injury" contiene "fatal".

In [49]:
attacks["fatal_y_or_n"].value_counts()

N          4301
Y          1441
NAN         487
UNKNOWN      73
Name: fatal_y_or_n, dtype: int64

Ahora cambiaremos el resto de valores "NAN" por "UNKNOWN" porque no podemos garantizar que no contaminamos los datos si los incluimos en alguna otra categor√≠a (no tenemos informaci√≥n veraz para incluirlos en "Y" o "N").

In [50]:
def unknown2 (i):
    if i == "NAN":
        return "UNKNOWN"
    else:
        return i

In [51]:
attacks["fatal_y_or_n"] = attacks["fatal_y_or_n"].apply(unknown2)

Observamos como todos los valores que antes eran "NAN" se han reemplazado por "UNKNOWN".

In [52]:
attacks["fatal_y_or_n"].value_counts()

N          4301
Y          1441
UNKNOWN     560
Name: fatal_y_or_n, dtype: int64

Ya tenemos los datos de la columna "fatal_y_or_n" preparados para poder trabajar con ellos y comprobar nuestra segunda hip√≥tesis.

In [53]:
attacks.to_csv("data/attacks_clean_def.csv", index=False) #Exportamos el DataFrame limpio.

En principio, con tener las columnas "activity" y "fatal_y_or_n" completamente limpias ya ser√≠a suficiente para poder generar visualizaciones y comprobar las hip√≥tesis planteadas.

Aunque tambi√©n hemos hecho una peque√±a limpieza general, es cierto que el resto de columnas siguen estando bastante sucias. Aun as√≠, por motivos de optimizaci√≥n de tiempo, empezamos a trabajar con estos datos y ya despu√©s, si queremos, seguiremos limpiando el resto de columnas del DataFrame.

Si despu√©s de cubrir los objetivos del proyecto (comprobar si las hip√≥tesis se cumplen o no se cumplen) seguimos teniendo tiempo, podremos seguir depurando los datos.